"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
  { on = "<C-u>", run = "arrow -75%", desc = "Move cursor up 3/4 page" },
  { on = "<C-d>", run = "arrow 75%", desc = "Move cursor down 3/4 page" },
  { on = "<C-b>", run = "seek -10", desc = "Seek up 10 units in the preview" },
  { on = "<C-f>", run = "seek 10", desc = "Seek down 10 units in the preview" },
]
