__RESET="\[$(tput sgr0)\]"
# reds
__RED="\[$(tput setaf 160)\]"
__LIGHT_RED="\[$(tput setaf 162)\]"
__DARK_RED="\[$(tput setaf 1)\]"
__NEON_RED="\[$(tput setaf 196)\]"
__ORANGE="\[$(tput setaf 166)\]"
__LIGHT_ORANGE="\[$(tput setaf 214)\]"
__DARK_ORANGE="\[$(tput setaf 130)\]"
# green yellows
__GREEN="\[$(tput setaf 2)\]"
__LIGHT_GREEN="\[$(tput setaf 46)\]"
__DARK_GREEN="\[$(tput setaf 22)\]"
__NEON_GREEN="\[$(tput setaf 46)\]"
__YELLOW="\[$(tput setaf 3)\]"
__LIGHT_YELLOW="\[$(tput setaf 227)\]"
__DARK_YELLOW="\[$(tput setaf 142)\]"
__NEON_YELLOW="\[$(tput setaf 154)\]"
# blue purple
__BLUE="\[$(tput setaf 4)\]"
__LIGHT_BLUE="\[$(tput setaf 45)\]"
__DARK_BLUE="\[$(tput setaf 18)\]"
__BLUE_GREEN="\[$(tput setaf 40)\]"
__PURPLE="\[$(tput setaf 5)\]"
__LIGHT_PURPLE="\[$(tput setaf 147)\]"
__DARK_PURPLE="\[$(tput setaf 57)\]"
__PURPLE_RED="\[$(tput setaf 126)\]"
__TEAL="\[$(tput setaf 6)\]"
# black white
__GREY="\[$(tput setaf 8)\]"
__LIGHT_GREY="\[$(tput setaf 249)\]"
__DARK_GREY="\[$(tput setaf 239)\]"
__DARK_WHITE="\[$(tput setaf 251)\]"
__BLACK="\[$(tput setaf 232)\]"
__LIGHT_BLACK="\[$(tput setaf 236)\]"

