# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
os:
  editPreset: "nvim-remote"
gui:
  border: rounded
  nerdFontsVersion: "3"
git:
  paging:
    colorArg: always
    useConfig: false
  overrideGpg: true
