[tool.ruff]
target-version = "py310"
line-length = 88
dummy-variable-rgx = "^_$"
fix = true
ignore-init-module-imports = true
select = ["D", "E", "F", "I", "Q"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.flake8-quotes]
inline-quotes = "double"

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.isort]
lines-between-types = 1

[tool.ruff.pydocstyle]
convention = "google"
